apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  DB_PASSWORD: bankpassword
  JWT_SECRET: supersecretjwt
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: banking
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpXSnlZV2hwYlhwaGVXVmtPbVJqYTNKZmNHRjBYM2hRTVZSUGFsQm9NR2ROV0ZGWlgxRm1iR1puT1ROVmJqQkhUUT09IgoJCX0KCX0KfQ==