apiVersion: v1
kind: ConfigMap
metadata:
  name: api-nginx-config
  namespace: banking
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location /api {
        default_type application/json;
        return 200 '{"status":"ok","service":"banking-api","message":"Mock API is running","accounts":[{"name":"Ibrahim","balance":12450}],"transactions":[{"type":"deposit","amount":2500},{"type":"payment","amount":120}]}';
      }

      location / {
        default_type application/json;
        return 200 '{"status":"ok","message":"Use /api"}';
      }
    }